<a href="https://colab.research.google.com/github/PosgradoMNA/actividades-de-aprendizaje-VictorRegueira/blob/main/IBM_Curso/IBM_Python_Mod5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Módulo 5

Víctor Alejandro Regueira Romero - A01794404

---

## IBM Course

In [3]:
import numpy as np
np.array([1,-1])*np.array([1,1])

array([ 1, -1])

In [4]:
np.dot(np.array([1,-1]),np.array([1,1]))

0

---

In [5]:
A = np.array([[1,2],[3,4],[5,6],[7,8]])
A.shape

(4, 2)

In [7]:
#A = np.array([[1,2],[3,4],[5,6],[7,8]])

#B = np.array([[1,2,3],[4,5,6],[7,8,9]])

#np.dot(A,B) 

---

In [9]:
a=np.array([0,1,0,1,0])

b=np.array([1,0,1,0,1])

a*b

array([0, 0, 0, 0, 0])

In [10]:
a=np.array([0,1])

b=np.array([1,0])

np.dot(a,b)

0

In [11]:
a=np.array([1,1,1,1,1])

a+10 

array([11, 11, 11, 11, 11])

## Labs

[PY0101EN-5-1-Numpy1D.ipynb](https://github.com/PosgradoMNA/actividades-de-aprendizaje-VictorRegueira/blob/main/IBM_Curso/Labs-Modulo5/PY0101EN-5-1-Numpy1D.ipynb)

[PY0101EN-5-2-Numpy2D.ipynb](https://github.com/PosgradoMNA/actividades-de-aprendizaje-VictorRegueira/blob/main/IBM_Curso/Labs-Modulo5/PY0101EN-5-2-Numpy2D.ipynb)

[PY0101EN-5.3_Requests_HTTP.ipynb](https://github.com/PosgradoMNA/actividades-de-aprendizaje-VictorRegueira/blob/main/IBM_Curso/Labs-Modulo5/PY0101EN-5.3_Requests_HTTP.ipynb)

## Quiz

[5.1_notebook_quizz_numpy1d.jupyterlite.ipynb](https://github.com/PosgradoMNA/actividades-de-aprendizaje-VictorRegueira/blob/main/IBM_Curso/Labs-Modulo5/5.1_notebook_quizz_numpy1d.jupyterlite.ipynb)

[5.2_notebook_quizz_numpy.jupyterlite](https://github.com/PosgradoMNA/actividades-de-aprendizaje-VictorRegueira/blob/main/IBM_Curso/Labs-Modulo5/5.2_notebook_quizz_numpy.jupyterlite.ipynb)